### ISSUE TITLE
Creating child theme of stout

### ISSUE THREAD

**Issue by GitHubGreg** [godaddy/wp-stout-theme#21]
Creating a child theme of Stout doesn't work because it is based on Primer. My child theme css looks like this:

```
@charset "UTF-8";

/*
Theme Name: Stout (Child)
Template: primer
*/

@import url("../stout/style.css");
```

The end result is a page that doesn't quite look like the Primer theme, and definitely doesn't look like the Stout theme. Any idea how to achieve a proper child theme of Stout?

**Comment by jonathanbardo** [comment]
@GitHubGreg You might want to take a look at a custom css plugin like this one https://en-ca.wordpress.org/plugins/simple-custom-css/ since there is no support for 2 level of child themes in WordPress core.

**Comment by GitHubGreg** [comment]
Thanks Jonathan. That would help for styling, but I also need to customize functions which would need to go in a child theme.

**Comment by jonathanbardo** [comment]
@GitHubGreg If you need to create custom functions then I would strongly suggest you create a small custom plugin. This might help you in your quest. https://en-ca.wordpress.org/plugins/pluginception/

**Comment by GitHubGreg** [comment]
Ok, thank you Jonathan. I have used a custom plugin to handle my functions and css.
