### ISSUE TITLE
Can't see + and - in mobile menu on iPhone

### ISSUE THREAD

**Issue by GitHubGreg** [godaddy/wp-stout-theme#23]
When viewing the navigation menu on an iPhone, the + is not visible on the right side of parent menu items. If you click where the + should be, then it shows the - sign (and clicking again shows the + sign) but with a grey background.

This can also be confirmed using Chrome's iPhone emulator.

**Comment by jonathanbardo** [comment]
Hey @GitHubGreg,

Thanks for reporting this, I will issue a patch in a few minutes.

Here is the new behavior:

<img width="534" alt="screen_shot_2016-11-21_at_1_23_38_pm" src="https://cloud.githubusercontent.com/assets/1933681/20495329/9ba245b4-afee-11e6-81fa-96d43af4f099.png">

**Comment by GitHubGreg** [comment]
Much appreciated @jonathanbardo , thanks for the quick turnaround.

**Comment by EvanHerman** [comment]
@GitHubGreg I believe this was fixed in [6a422bd](https://github.com/godaddy/wp-stout-theme/commit/6a422bded6194a1d965a33d5629ae6edac7e7739). If you are still encountering issues, don't hesitate to reach back out.
