### ISSUE TITLE
Question: Changing breakpoint for mobile menu

### ISSUE THREAD

**Issue by GitHubGreg** [godaddy/wp-stout-theme#25]
This is a question rather than an issue. 

I would like the mobile menu to appear sooner (at a larger width) and can't find a simple way to change the CSS breakpoints.

I have a normal-size navigation menu (four page names) but it collides with the logo at around 700px and goes onto a new line. Ideally, it would become a mobile menu (hamburger icon) sooner.

Looking at the theme CSS, it seems that the mobile breakpoint is at 40.063 em. This seems to be the framework used by [Foundation](http://foundation.zurb.com/sites/docs/v/5.5.3/media-queries.html).

Trying to do a find-replace of this value with a larger value didn't work unfortunately. Can you please recommend a quick way to have the mobile menu appear sooner (at a larger width)?

Thanks.

**Comment by jonathanbardo** [comment]
Hey @GitHubGreg,

The straight answer would be to rework the css using a custom css plugin and rework the media queries. 

I currently don't have much time to dig into that but you are welcome to do a Pull Request if you find a solution that would fit everyone.

**Comment by fjarrett** [comment]
If you're not concerned about IE10 support, you could possibly look into applying Flexox properties to the desktop menu items so they contract with the viewport width.

https://css-tricks.com/snippets/css/a-guide-to-flexbox/
