### ISSUE TITLE
Remove header on one page?

### ISSUE THREAD

**Issue by Tanooks** [godaddy/wp-stout-theme#26]
Basically the title. How do I remove the header (title and image) from a page?

**Comment by EvanHerman** [comment]
Hi @Tanooks ,

To remove the header on a single page you'll need to write some custom code. You'll want to create an `mu-plugin` where you can add the custom code to.

We have written a tutorial in the Wiki for the parent theme Primer.
https://github.com/godaddy/wp-primer-theme/wiki/customizing-primer-with-hooks#how-to-create-a-must-use-plugin

Here is some example of code to get you started, which would hide the header form:


```php
function hide_header() {

	global $post;

	if ( 70 !== $post->ID ) {

		return;

	}

	remove_action( 'primer_header', 'primer_add_site_title', 5 );

}
add_action( 'wp_head', 'hide_header' );
```

You'll want to swap out 70 in the code above with the page ID value that you want to remove the header from.

Let us know how that works for you.


Evan
