### ISSUE TITLE
Dropdown bug

### ISSUE THREAD

**Issue by fjarrett** [godaddy/wp-stout-theme#28]
_From @scottalai on February 7, 2017 17:42_

I am using the Stout child theme and I have two dropdown menus. They work fine fullscreen, but if you shrink down the browser window size a little, the second dropdown stays on the screen after you hover over it and won't close automatically like it is supposed to. 

_Copied from original issue: godaddy/wp-primer-theme#151_

**Comment by fjarrett** [comment]
_From @EvanHerman on February 7, 2017 17:50_

Hi @scottalai 

I can see the bug on my end, on your site. I will take a look and see if I can replicate it on a test instance that I have setup and see what might be going on.

Evan

**Comment by fjarrett** [comment]
_From @EvanHerman on February 7, 2017 20:25_

Hi @scottalai 

I have a fresh WordPress install running the stout theme with a similar navigation to what you have setup, and I'm not running into that issue.

What plugins do you have installed on your site? Maybe I can setup a test instance that closer matches yours.

**Update:**
I am seeing the issue now after shifting things around a bit. I'll try and dig in here and see what's going on.

**Comment by fjarrett** [comment]
@scottalai No need for credentials, logging in to user installs and performing work is outside the scope of this support channel. We are investigating the issue you described and attempting to reproduce locally. Thanks for reporting it!

**Comment by fjarrett** [comment]
_From @EvanHerman on February 8, 2017 0:8_

@scottalai I have been able to reproduce it locally, I am investigating the issue. I can't see anything that would be causing the issue from a quick look through, but I will keep investigating and will update this thread as I discover more information.

**Comment by fjarrett** [comment]
_From @scottalai on February 13, 2017 17:26_

I have not heard any news for 6 days now. I really need this glitch fixed. My client is not pleased that the site does not work properly.

**Comment by fjarrett** [comment]
Hey @scottalai - Our free themes don't have an SLA, though we do try our best to reproduce and fix reported issues as fast as we can so everyone using them can benefit. If you have business-critical needs we would advise considering a premium paid theme from a WP theme shop that has guaranteed response times.

Some tips on helping make things go faster:

- List the active plugins you are using
- Give us any custom CSS you might be using
- Provide screenshots (when applicable)
- If you are a developer, give us insight into what things you've attempted to solve the problem - in other words, have you done any troubleshooting?

**Comment by fjarrett** [comment]
_From @scottalai on February 13, 2017 19:12_

I did list the plugins and provided screenshots. EvanHerman said he was able to reproduce the problem locally.

**Comment by fjarrett** [comment]
@scottalai I'm not seeing that information anywhere on this thread... did a separate discussion take place elsewhere?

**Comment by fjarrett** [comment]
_From @scottalai on February 13, 2017 21:57_

![bug](https://cloud.githubusercontent.com/assets/25617039/22905219/8a5aecf0-f20d-11e6-9eda-9db4538b1320.jpg)
![plugins](https://cloud.githubusercontent.com/assets/25617039/22905220/8a60145a-f20d-11e6-9c1d-83692c4a7ce3.jpg)

**Comment by scottalai** [comment]
I would hope that a company that was hired by a big company like GoDaddy to develop a Theme for said company would care about a little glitch, seeing that A LOT OF PEOPLE  will be using your theme/code.

**Comment by fjarrett** [comment]
@scottalai We build and maintain our free themes internally here at GoDaddy, we are not contractors. We take glitches seriously and sincerely appreciate you for reporting it!

**Comment by scottalai** [comment]
You are not GoDaddy. I can tell you don't care by the way you talk a lot and don't do anything. If I made a Theme for a huge company like GoDaddy....I'd make sure it worked.

**Comment by fjarrett** [comment]
@scottalai Thanks for the feedback. It sounds like somewhere along the way I may have offended you - I'm sorry that was definitely not my intention. Just want to stay transparent about expectations, response times, etc relating to our themes. We do care, and we do want to resolve issues as fast as we can.

**Comment by scottalai** [comment]
Less talk more action. EvanHerman said he saw the problem and was working on it. How is that going?

**Comment by EvanHerman** [comment]
@scottalai It is going well. I am actively working on the issue and have narrowed it down to a few lines of JavaScript code in the navigation script. Now I am working on patching it.

**Comment by EvanHerman** [comment]
@scottalai Patch has been proposed in the pull request mentioned above. If you would like, feel free to take a look at the files changed if you need to implement an immediate solution. 

This will need to be reviewed and most likely merged into the upcoming v1.5.0 release of Primer (since this was a Primer parent theme bug).
