### ISSUE TITLE
When changing color scheme hero button blends into the hero background

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-stout-theme#3]
It might be good to have some contrast between the background color on the default scheme.

![screen shot 2016-08-12 at 11 23 03 am](https://cloud.githubusercontent.com/assets/1933681/17627411/278c5b9c-607f-11e6-952b-fc1c6606eabb.png)

**Comment by chriswallace** [comment]
It looks like this was fixed already.
