### ISSUE TITLE
Full-width page builder element stay fixed-width

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-stout-theme#4]
Even if you choose full-width on an element in beaver builder, it stays fixed width.

![screen_shot_2016-08-12_at_11_25_40_am](https://cloud.githubusercontent.com/assets/1933681/17627565/b1d82484-607f-11e6-9ebf-a0f8c047499a.png)

**Comment by chriswallace** [comment]
I'm not seeing this anywhere. Can you either provide steps to reproduce or close this issue if no longer applicable.
