### ISSUE TITLE
Menu not open in Safari + iPhone

### ISSUE THREAD

**Issue by LuisMigueldelCorral** [godaddy/wp-stout-theme#51]
I do not know if it's possible for someone to confirm if the menu is displayed correctly on iPhone + Safari, maybe it is some configuration of my wordpress but I wanted to confirm before that it is not a problem of the theme.

My website is [fuencarraltm.es](http://fuencarraltm.es) I would appreciate any comments.

Regards

<hr>

No se si es posible que alguien me confirme que el menu se despliega correctamente en iPhone + Safari, quizás sea alguna configuración de mi wordpress pero queria confirmar antes que no es un problema del tema.

Mi web es [fuencarraltm.es](http://fuencarraltm.es) agredeceria cualquier comentario.

Saludos

**Comment by EvanHerman** [comment]
Hi @LuisMigueldelCorral 

I am also seeing the same issue on your website, however I'm not seeing it on our test site at https://wpnux.godaddy.com/?theme=stout

Can you try trimming down the length of your site title next to the menu button to see if that helps? If not, it's possible there is another conflict on your site that is a bit trickier to debug on iOS devices.

I opened your site in an iPhone simulator on my local machine and was able to see the following javascript error in the console:

```javascript
 Syntax error, unrecognized expression: .carga-ranking a, a[href^="http://www.fedmadtm.com"
```

Does that look familiar to you?

**Comment by LuisMigueldelCorral** [comment]
In effect, the problem was in the plugin that you indicated.

Thanks @EvanHerman

**Comment by EvanHerman** [comment]
Great, no problem at all @LuisMigueldelCorral. I'm glad that we could help pinpoint the issue and it wasn't some larger issue at hand.

I hope you have a great week!
