### ISSUE TITLE
Is it possible to use custom homepage and hero widget?

### ISSUE THREAD

**Issue by cbzink** [godaddy/wp-stout-theme#52]
Is it possible to use both the hero widget (with call to action) _and_ a custom homepage?

It seems when I go to customize and change the home page options from "latest posts" to a custom page, my homepage widget disappears and it either inherits the page title, or I can specify another page for the hero but lose the ability to have a call to action.

Thanks!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
