### ISSUE TITLE
Fluid Layout

### ISSUE THREAD

**Issue by naomijean** [godaddy/wp-stout-theme#55]
The navigation does not change when the "Fluid Layout" option is selected; the body changes to full-width and the navigation does not. I have been messing with the code, trying to create "no max width" on the nav bar and I cannot get it to work.

**Comment by naomijean** [comment]
Never mind! I think I got it to work.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
