### ISSUE TITLE
Reading Setting "for each article in a feed, show" not changing

### ISSUE THREAD

**Issue by pkimzey** [godaddy/wp-stout-theme#57]
In Reading Settings I want to display full text on my blog page. Changing the setting from summary to full text for my article feed does not update. I've tried changing and saving this setting for each but the feed display does not change. The "read more" function on the post has no effect and using the excerpt feature is not a solution.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
